//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaarrRescueMission.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaarrRescueMission.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CaptionAppTitle {
            get {
                return ResourceManager.GetString("CaptionAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asteroids.
        /// </summary>
        internal static string CaptionAsteroids {
            get {
                return ResourceManager.GetString("CaptionAsteroids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache-control.
        /// </summary>
        internal static string CaptionCacheControl {
            get {
                return ResourceManager.GetString("CaptionCacheControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaarr.
        /// </summary>
        internal static string CaptionChaarr {
            get {
                return ResourceManager.GetString("CaptionChaarr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://chaarr.future-processing.pl/describe?login=marcin.chilicki96@gmail.com.google&amp;token=6C35BC6A4453674C7BA4E0A9E776BEF0.
        /// </summary>
        internal static string CaptionChaarrDescribe {
            get {
                return ResourceManager.GetString("CaptionChaarrDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://chaarr.future-processing.pl/execute.
        /// </summary>
        internal static string CaptionChaarrExecute {
            get {
                return ResourceManager.GetString("CaptionChaarrExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chaarrHatred.
        /// </summary>
        internal static string CaptionChaarrHatred {
            get {
                return ResourceManager.GetString("CaptionChaarrHatred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communications.
        /// </summary>
        internal static string CaptionCommunications {
            get {
                return ResourceManager.GetString("CaptionCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-type.
        /// </summary>
        internal static string CaptionContentType {
            get {
                return ResourceManager.GetString("CaptionContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crewDeaths.
        /// </summary>
        internal static string CaptionCrewDeaths {
            get {
                return ResourceManager.GetString("CaptionCrewDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        internal static string CaptionDecoy {
            get {
                return ResourceManager.GetString("CaptionDecoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string CaptionEnergy {
            get {
                return ResourceManager.GetString("CaptionEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipments.
        /// </summary>
        internal static string CaptionEquipments {
            get {
                return ResourceManager.GetString("CaptionEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esthajnalcsillag.
        /// </summary>
        internal static string CaptionEsthajnalcsillag {
            get {
                return ResourceManager.GetString("CaptionEsthajnalcsillag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvacScience.
        /// </summary>
        internal static string CaptionEvacScience {
            get {
                return ResourceManager.GetString("CaptionEvacScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvacSurvivors.
        /// </summary>
        internal static string CaptionEvacSurvivors {
            get {
                return ResourceManager.GetString("CaptionEvacSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaarrHatredChanged.
        /// </summary>
        internal static string CaptionEventChaarrHatredChanged {
            get {
                return ResourceManager.GetString("CaptionEventChaarrHatredChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrewDeathsChanged.
        /// </summary>
        internal static string CaptionEventCrewDeathsChanged {
            get {
                return ResourceManager.GetString("CaptionEventCrewDeathsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpeditionEnergyChanged.
        /// </summary>
        internal static string CaptionEventExpeditionEnergyChanged {
            get {
                return ResourceManager.GetString("CaptionEventExpeditionEnergyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpeditionMatterChanged.
        /// </summary>
        internal static string CaptionEventExpeditionMatterChanged {
            get {
                return ResourceManager.GetString("CaptionEventExpeditionMatterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnowledgeChanged.
        /// </summary>
        internal static string CaptionEventKnowledgeChanged {
            get {
                return ResourceManager.GetString("CaptionEventKnowledgeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEnoughMinerals.
        /// </summary>
        internal static string CaptionEventNotEnoughMinerals {
            get {
                return ResourceManager.GetString("CaptionEventNotEnoughMinerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PołudnicaEnergyChanged.
        /// </summary>
        internal static string CaptionEventPołudnicaEnergyChanged {
            get {
                return ResourceManager.GetString("CaptionEventPołudnicaEnergyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PołudnicaMatterChanged.
        /// </summary>
        internal static string CaptionEventPołudnicaMatterChanged {
            get {
                return ResourceManager.GetString("CaptionEventPołudnicaMatterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        internal static string CaptionEvents {
            get {
                return ResourceManager.GetString("CaptionEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurvivorDeathsChanged.
        /// </summary>
        internal static string CaptionEventSurvivorDeathsChanged {
            get {
                return ResourceManager.GetString("CaptionEventSurvivorDeathsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpkeepTime.
        /// </summary>
        internal static string CaptionEventUpkeepTime {
            get {
                return ResourceManager.GetString("CaptionEventUpkeepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expeditionEnergy.
        /// </summary>
        internal static string CaptionExpeditionEnergy {
            get {
                return ResourceManager.GetString("CaptionExpeditionEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expeditionMatter.
        /// </summary>
        internal static string CaptionExpeditionMatter {
            get {
                return ResourceManager.GetString("CaptionExpeditionMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalWar.
        /// </summary>
        internal static string CaptionFinalWar {
            get {
                return ResourceManager.GetString("CaptionFinalWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest.
        /// </summary>
        internal static string CaptionHarvest {
            get {
                return ResourceManager.GetString("CaptionHarvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string CaptionHelp {
            get {
                return ResourceManager.GetString("CaptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string CaptionJsonApp {
            get {
                return ResourceManager.GetString("CaptionJsonApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knowledge.
        /// </summary>
        internal static string CaptionKnowledge {
            get {
                return ResourceManager.GetString("CaptionKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastTurnEvents.
        /// </summary>
        internal static string CaptionLastTurnEvents {
            get {
                return ResourceManager.GetString("CaptionLastTurnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string CaptionLocation {
            get {
                return ResourceManager.GetString("CaptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logBook.
        /// </summary>
        internal static string CaptionLogBook {
            get {
                return ResourceManager.GetString("CaptionLogBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marcin.chilicki96@gmail.com.google.
        /// </summary>
        internal static string CaptionLogin {
            get {
                return ResourceManager.GetString("CaptionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180.
        /// </summary>
        internal static string CaptionMaxChaarrHatred {
            get {
                return ResourceManager.GetString("CaptionMaxChaarrHatred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoveTo.
        /// </summary>
        internal static string CaptionMove {
            get {
                return ResourceManager.GetString("CaptionMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-cache.
        /// </summary>
        internal static string CaptionNoCache {
            get {
                return ResourceManager.GetString("CaptionNoCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string CaptionOrder {
            get {
                return ResourceManager.GetString("CaptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string CaptionParameters {
            get {
                return ResourceManager.GetString("CaptionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partialshuttle.
        /// </summary>
        internal static string CaptionPartialshuttle {
            get {
                return ResourceManager.GetString("CaptionPartialshuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Południca.
        /// </summary>
        internal static string CaptionPołudnica {
            get {
                return ResourceManager.GetString("CaptionPołudnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poludnicaEnergy.
        /// </summary>
        internal static string CaptionPoludnicaEnergy {
            get {
                return ResourceManager.GetString("CaptionPoludnicaEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poludnicaMatter.
        /// </summary>
        internal static string CaptionPoludnicaMatter {
            get {
                return ResourceManager.GetString("CaptionPoludnicaMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce.
        /// </summary>
        internal static string CaptionProduce {
            get {
                return ResourceManager.GetString("CaptionProduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string CaptionRepair {
            get {
                return ResourceManager.GetString("CaptionRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string CaptionRestart {
            get {
                return ResourceManager.GetString("CaptionRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreat.
        /// </summary>
        internal static string CaptionRetreat {
            get {
                return ResourceManager.GetString("CaptionRetreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedScience.
        /// </summary>
        internal static string CaptionSavedScience {
            get {
                return ResourceManager.GetString("CaptionSavedScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedSurvivors.
        /// </summary>
        internal static string CaptionSavedSurvivors {
            get {
                return ResourceManager.GetString("CaptionSavedSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string CaptionScan {
            get {
                return ResourceManager.GetString("CaptionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scores.
        /// </summary>
        internal static string CaptionScore {
            get {
                return ResourceManager.GetString("CaptionScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crewMalus.
        /// </summary>
        internal static string CaptionScoreCrewMalus {
            get {
                return ResourceManager.GetString("CaptionScoreCrewMalus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventScore.
        /// </summary>
        internal static string CaptionScoreEvent {
            get {
                return ResourceManager.GetString("CaptionScoreEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knowledgeScore.
        /// </summary>
        internal static string CaptionScoreKnowledge {
            get {
                return ResourceManager.GetString("CaptionScoreKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scienceScore.
        /// </summary>
        internal static string CaptionScoreScience {
            get {
                return ResourceManager.GetString("CaptionScoreScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survivorsScore.
        /// </summary>
        internal static string CaptionScoreSurvivors {
            get {
                return ResourceManager.GetString("CaptionScoreSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totalScore.
        /// </summary>
        internal static string CaptionScoreTotal {
            get {
                return ResourceManager.GetString("CaptionScoreTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttle.
        /// </summary>
        internal static string CaptionShuttle {
            get {
                return ResourceManager.GetString("CaptionShuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuttlewrench.
        /// </summary>
        internal static string CaptionShuttlewrench {
            get {
                return ResourceManager.GetString("CaptionShuttlewrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        internal static string CaptionSimulation {
            get {
                return ResourceManager.GetString("CaptionSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://simulation.future-processing.pl/describe?login=marcin.chilicki96@gmail.com.google&amp;token=6C35BC6A4453674C7BA4E0A9E776BEF0.
        /// </summary>
        internal static string CaptionSimulationDescribe {
            get {
                return ResourceManager.GetString("CaptionSimulationDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://simulation.future-processing.pl/execute.
        /// </summary>
        internal static string CaptionSimulationExecute {
            get {
                return ResourceManager.GetString("CaptionSimulationExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies.
        /// </summary>
        internal static string CaptionSupplies {
            get {
                return ResourceManager.GetString("CaptionSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string CaptionSuppliesDefault {
            get {
                return ResourceManager.GetString("CaptionSuppliesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survivorDeaths.
        /// </summary>
        internal static string CaptionSurvivorDeaths {
            get {
                return ResourceManager.GetString("CaptionSurvivorDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedSurvivors.
        /// </summary>
        internal static string CaptionSurvivors {
            get {
                return ResourceManager.GetString("CaptionSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6C35BC6A4453674C7BA4E0A9E776BEF0.
        /// </summary>
        internal static string CaptionToken {
            get {
                return ResourceManager.GetString("CaptionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string CaptionTools {
            get {
                return ResourceManager.GetString("CaptionTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn.
        /// </summary>
        internal static string CaptionTurn {
            get {
                return ResourceManager.GetString("CaptionTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string CaptionWeapons {
            get {
                return ResourceManager.GetString("CaptionWeapons", resourceCulture);
            }
        }
    }
}
