//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaarrRescueMission.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaarrRescueMission.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache-control.
        /// </summary>
        internal static string CaptionCacheControl {
            get {
                return ResourceManager.GetString("CaptionCacheControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaarr Hatred.
        /// </summary>
        internal static string CaptionChaarrHatred {
            get {
                return ResourceManager.GetString("CaptionChaarrHatred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content-type.
        /// </summary>
        internal static string CaptionContentType {
            get {
                return ResourceManager.GetString("CaptionContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Deaths.
        /// </summary>
        internal static string CaptionCrewDeaths {
            get {
                return ResourceManager.GetString("CaptionCrewDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        internal static string CaptionEquipments {
            get {
                return ResourceManager.GetString("CaptionEquipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string CaptionEvents {
            get {
                return ResourceManager.GetString("CaptionEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition Energy.
        /// </summary>
        internal static string CaptionExpeditionEnergy {
            get {
                return ResourceManager.GetString("CaptionExpeditionEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expedition Matter.
        /// </summary>
        internal static string CaptionExpeditionMatter {
            get {
                return ResourceManager.GetString("CaptionExpeditionMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://simulation.future-processing.pl/describe?login=marcin.chilicki96@gmail.com.google&amp;token=6C35BC6A4453674C7BA4E0A9E776BEF0.
        /// </summary>
        internal static string CaptionGET {
            get {
                return ResourceManager.GetString("CaptionGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string CaptionJsonApp {
            get {
                return ResourceManager.GetString("CaptionJsonApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        internal static string CaptionKnowledge {
            get {
                return ResourceManager.GetString("CaptionKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Turn Events.
        /// </summary>
        internal static string CaptionLastTurnEvents {
            get {
                return ResourceManager.GetString("CaptionLastTurnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string CaptionLocation {
            get {
                return ResourceManager.GetString("CaptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Book.
        /// </summary>
        internal static string CaptionLogBook {
            get {
                return ResourceManager.GetString("CaptionLogBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marcin.chilicki96@gmail.com.
        /// </summary>
        internal static string CaptionLogin {
            get {
                return ResourceManager.GetString("CaptionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-cache.
        /// </summary>
        internal static string CaptionNoCache {
            get {
                return ResourceManager.GetString("CaptionNoCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string CaptionParameters {
            get {
                return ResourceManager.GetString("CaptionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poludnica Energy.
        /// </summary>
        internal static string CaptionPoludnicaEnergy {
            get {
                return ResourceManager.GetString("CaptionPoludnicaEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poludnica Matter.
        /// </summary>
        internal static string CaptionPoludnicaMatter {
            get {
                return ResourceManager.GetString("CaptionPoludnicaMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://simulation.future-processing.pl/execute.
        /// </summary>
        internal static string CaptionPOST {
            get {
                return ResourceManager.GetString("CaptionPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Science.
        /// </summary>
        internal static string CaptionSavedScience {
            get {
                return ResourceManager.GetString("CaptionSavedScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Survivors.
        /// </summary>
        internal static string CaptionSavedSurvivors {
            get {
                return ResourceManager.GetString("CaptionSavedSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        internal static string CaptionScore {
            get {
                return ResourceManager.GetString("CaptionScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Malus.
        /// </summary>
        internal static string CaptionScoreCrewMalus {
            get {
                return ResourceManager.GetString("CaptionScoreCrewMalus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Score.
        /// </summary>
        internal static string CaptionScoreEvent {
            get {
                return ResourceManager.GetString("CaptionScoreEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Score.
        /// </summary>
        internal static string CaptionScoreKnowledge {
            get {
                return ResourceManager.GetString("CaptionScoreKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Scores.
        /// </summary>
        internal static string CaptionScoreScience {
            get {
                return ResourceManager.GetString("CaptionScoreScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivors Scores.
        /// </summary>
        internal static string CaptionScoreSurvivors {
            get {
                return ResourceManager.GetString("CaptionScoreSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        internal static string CaptionScoreTotal {
            get {
                return ResourceManager.GetString("CaptionScoreTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor Deaths.
        /// </summary>
        internal static string CaptionSurvivorDeaths {
            get {
                return ResourceManager.GetString("CaptionSurvivorDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Survivors.
        /// </summary>
        internal static string CaptionSurvivors {
            get {
                return ResourceManager.GetString("CaptionSurvivors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6C35BC6A4453674C7BA4E0A9E776BEF0.
        /// </summary>
        internal static string CaptionToken {
            get {
                return ResourceManager.GetString("CaptionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        internal static string CaptionTurn {
            get {
                return ResourceManager.GetString("CaptionTurn", resourceCulture);
            }
        }
    }
}
